### ISSUE TITLE
伏せる機能

### ISSUE THREAD

**Issue by tabnyan1** [laco0416/SmileEssence#74]
”ゆるゆり”→伏せるコマンド→”ゆる○り”

”野々村県議「誰がﾃﾞｰ！ﾀﾞﾃﾞﾆ投票しても！ｵﾝﾅｼﾞﾔｵﾝﾅｼﾞﾔｵﾓﾃｰ！ ﾝｧｯ↑ﾊｯﾊｯﾊｯﾊｰｗｗｗｗｗｗｱ゛ﾝ！！ このﾆこのにほんﾝﾝﾝｯﾊｱｱｱｱｱｱｱｱｱ↑↑↑ｱｧﾝ！！！！！！ｱｩｯｱｩｵｩ ｳｱ゛ｱｱｱｱｱｱｱｱｱｱｱｱｱーーー！！！ｱｳｱｳ！ｺﾉﾋﾎﾝｧｩｧｩ…… 以下略」”
→伏せるコマンド
→”野々○県議「誰がﾃﾞｰ！ﾀﾞﾃﾞﾆ投票しても！ｵﾝﾅｼﾞﾔｵﾝﾅｼﾞﾔｵﾓﾃｰ！ ﾝｧｯ↑ﾊｯﾊｯﾊｯﾊｰｗｗｗｗｗｗｱ゛ﾝ！！ このﾆこのにほんﾝﾝﾝｯﾊｱｱｱｱｱｱｱｱｱ↑↑↑ｱｧﾝ！！！！！！ｱｩｯｱｩｵｩ ｳｱ゛ｱｱｱｱｱｱｱｱｱｱｱｱｱーーー！！！ｱｳｱｳ！ｺﾉﾋﾎﾝｧｩｧｩ…… 以下略」”

**Comment by laco0416** [comment]
あまり面白くないので却下します
